Formatting

diff --git a/fs/magento/etc/services.d/magento/run b/fs/magento/etc/services.d/magento/run
--- a/fs/magento/etc/services.d/magento/run
+++ b/fs/magento/etc/services.d/magento/run
@@ -5,36 +5,36 @@ MAGENTO_MODE=${MAGENTO_MODE:-development}
 TASKSD_DIR="${DIRECTORY}/tasks.d"
 SECONDS=0
 function fixCachePerms() {
-    echo "[$DIR] Fixing cache ownership"
-    chown -R app:app /app/var
+	echo "[$DIR] Fixing cache ownership"
+	chown -R app:app /app/var
 }
 function runStartupTasks() {
-    if [ ! -d "$TASKSD_DIR" ]; then
-        echo "[$DIR] Tasks directory $TASKSD_DIR missing, skipping."
-        exit 0
-    fi
-    local task_count=$(find "$TASKSD_DIR" -maxdepth 1 -type f -name '*.sh' | wc -l)
-    if [ "$task_count" -eq 0 ]; then
-        echo "[$DIR:DevTasks] No development tasks found in $TASKSD_DIR, skipping."
-        exit 0
-    fi
-    echo "[$DIR:DevTasks] There are $task_count development tasks to run"
-    for script in "$TASKSD_DIR"/*.sh; do
-      echo "[$DIR:DevTasks]  > Running $script"
-      su -c "bash $script" app
-      if [ $? -ne 0 ]; then
-        echo "[$DIR:DevTasks]  > Error running $script"
-        exit 1
-      fi
-    done
-    # After running, we should probably fix the perms just in case.
-    fixCachePerms
+	if [ ! -d "$TASKSD_DIR" ]; then
+		echo "[$DIR] Tasks directory $TASKSD_DIR missing, skipping."
+		exit 0
+	fi
+	local task_count=$(find "$TASKSD_DIR" -maxdepth 1 -type f -name '*.sh' | wc -l)
+	if [ "$task_count" -eq 0 ]; then
+		echo "[$DIR:DevTasks] No development tasks found in $TASKSD_DIR, skipping."
+		exit 0
+	fi
+	echo "[$DIR:DevTasks] There are $task_count development tasks to run"
+	for script in "$TASKSD_DIR"/*.sh; do
+		echo "[$DIR:DevTasks]  > Running $script"
+		su -c "bash $script" app
+		if [ $? -ne 0 ]; then
+			echo "[$DIR:DevTasks]  > Error running $script"
+			exit 1
+		fi
+	done
+	# After running, we should probably fix the perms just in case.
+	fixCachePerms
 }
 
 touch /etc/services.d/magento/starting
-fixCachePerms;
+fixCachePerms
 echo "[$DIR] Starting Magento"
-runStartupTasks;
+runStartupTasks
 echo "[$DIR] Magento startup finished in $SECONDS seconds."
 rm /etc/services.d/magento/starting
 touch /etc/services.d/magento/done
