various bits of magento fiddling

diff --git a/fs/magento/etc/services.d/magento/run b/fs/magento/etc/services.d/magento/run
--- a/fs/magento/etc/services.d/magento/run
+++ b/fs/magento/etc/services.d/magento/run
@@ -6,6 +6,8 @@ source /usr/local/share/common.sh
 MAGENTO_MODE=${MAGENTO_MODE:-development}
 TASKSD_DIR="${CURRENT_DIR}/tasks.d"
 SECONDS=0
+rm /etc/services.d/magento/failed >/dev/null 2>&1 || true
+
 function fixCachePerms() {
 	echo "[$DIR] Fixing cache ownership"
 	chown -R app:app /app/var
@@ -23,9 +25,11 @@ function runStartupTasks() {
 	echo "[$DIR] There are ${COLOR_YELLOW}${task_count}${COLOR_RESET} development tasks to run"
 	for script in "$TASKSD_DIR"/*.sh; do
 		echo "[$DIR]  > Running ${COLOR_GREY}${script}${COLOR_RESET}"
-		su -c "bash $script" app
-		if [ $? -ne 0 ]; then
-			echo "[$DIR]  > Error running ${COLOR_GREY}${script}${COLOR_RESET}"
+		if su -c "bash $script; exit \$?" app; then
+			echo "[$DIR]  > ${COLOR_GREEN}Success${COLOR_RESET} running ${COLOR_GREY}${script}${COLOR_RESET}"
+		else
+			echo "[$DIR]  > ${COLOR_RED}Failed${COLOR_RESET} running ${COLOR_GREY}${script}${COLOR_RESET}"
+			touch /etc/services.d/magento/failed
 			exit 1
 		fi
 	done
diff --git a/fs/magento/usr/local/bin/healthcheck b/fs/magento/usr/local/bin/healthcheck
--- a/fs/magento/usr/local/bin/healthcheck
+++ b/fs/magento/usr/local/bin/healthcheck
@@ -3,4 +3,8 @@ if [ -f /etc/services.d/magento/starting ]; then
 	echo "Magento is starting up, healthcheck is not ready yet, spare the httpd the pain"
 	exit 0
 fi
+if [ -f /etc/services.d/magento/failed ]; then
+	echo "Magento startup failed critically, this container is doomed."
+	exit 1
+fi
 exec curl -f http://localhost:80
