Make cron group configurable

diff --git a/fs/magento/etc/services.d/cron/run b/fs/magento/etc/services.d/cron/run
--- a/fs/magento/etc/services.d/cron/run
+++ b/fs/magento/etc/services.d/cron/run
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 source /usr/local/share/common.sh
 (
-	CRON_INTERVAL_SECONDS=300 # Default cron interval in seconds
+	MAGENTO_CRON_INTERVAL_SECONDS=300 # Default cron interval in seconds
 	# wait until /etc/services.d/magento/done exists
 	if [ ! -f /etc/services.d/magento/done ]; then
 		echo "Waiting for Magento to be ready ..."
@@ -12,7 +12,7 @@ source /usr/local/share/common.sh
 	echo "Magento is ready, starting cron."
 
 	# Run once first to populate cron lists. If it fails, disable cron.
-	if ! chpst -u app magento cron:run; then
+	if ! chpst -u app magento cron:run --group "${MAGENTO_CRON_GROUP:-"default"}"; then
 		echo "[$DIR] Magento cron failed to run, disabling cron."
 		sleep infinity
 		exit 1
@@ -22,10 +22,10 @@ source /usr/local/share/common.sh
 	while true; do
 		(
 			flock -s 200
-			chpst -u app magento cron:run
+			chpst -u app magento cron:run --group "${MAGENTO_CRON_GROUP:-"default"}"
 		) 200>/var/run/magento-cron.lock || {
-			echo "[$DIR] Magento cron failed to run, retrying in $CRON_INTERVAL_SECONDS seconds."
+			echo "[$DIR] Magento cron failed to run, retrying in $MAGENTO_CRON_INTERVAL_SECONDS seconds."
 		}
-		sleep $CRON_INTERVAL_SECONDS
+		sleep $MAGENTO_CRON_INTERVAL_SECONDS
 	done
 ) 2>&1 | (while IFS= read -r; do echo "${COLOR_RESET}[${DIR}] $REPLY"; done)
